### ISSUE TITLE
Loading player achievements very slow

### ISSUE THREAD

**Issue by micheljung** [micheljung/faf-java-api#289]
https://api.faforever.com/data/playerAchievement

**Comment by Brutus5000** [comment]
This bug is serious because it effectively blocks the java client to show any user details while fetching the achievements for a single player.
I tested the plain SQL query for selecting the achievements and that only took a few milliseconds. However fetching the URL via postman it runs around 30 seconds. We need to investigate what Elide does and where it spends all the time.

Example call for postman: https://api.faforever.com/data/playerAchievement?filter=player.id=="245841"

**Comment by bukajsytlos** [comment]
This api call is doing select from player achievements and than N calls for each achievement which joins with achievements statistics which is heavy.
