### ISSUE TITLE
Migrate tests to JUnit 5

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#347]
Our tests already use JUnit5 runners with the compatibility runner for older versions.

Still many tests rely on old JUnit4 features (e.g. for temporary directories or rules for expecting exceptions etc.), which are reworked in JUnit 5.

As a result of this ticket, no more @Test annotation from `org.junit.Test` should be used (JUnit5 uses `org.junit.jupiter.api.Test`)

I would recommend `test` and `inttest` packages to be handled seperately and to do `test` first.

**Comment by Rhuancpq** [comment]
Can I try this one?

**Comment by Ikhiloya** [comment]
Hi, I'm new to OSS, I'd like to try this one. Though, I'll need guidance. Thanks

**Comment by Brutus5000** [comment]
Hey guys, I have added instructions to the readme how to setup our database, otherwise you can't run the test suite for the integration tests.

**Comment by nagavenkatakiran** [comment]
Hi Team,
I would like to resolve this issue

**Comment by 1-alex98** [comment]
Yeah well. I think as nobody really started working on it other than writing they would like to it is yours @nagavenkatakiran

**Comment by icougil** [comment]
Hi!
I've found that there was no news about this issue, and I've had a little free time...  
I found some issues running all the integration tests and I think it was because of the classpath that it was not correctly setup and that was the reason why I never found JUnit5 classes working in the integration folder.
Let me know what do you think: https://github.com/FAForever/faf-java-api/pull/352
Best,

**Comment by Brutus5000** [comment]
fixed by #352
