### ISSUE TITLE
FA featured mod is not updated as a whole

### ISSUE THREAD

**Issue by tatsujb** [micheljung/faf-java-api#353]
#The real issue :
https://github.com/FAForever/downlords-faf-client/issues/1095#issuecomment-515583795
--------------------------------------------------------------------------------------------
I get everything working except 1v1  and featured mods :  

![Screenshot from 2019-08-04 00-59-55](https://user-images.githubusercontent.com/5132359/62417579-39d03d00-b653-11e9-9e9b-c1ae492e9175.png)

```
Failed to setup initial search path.

Program : Z:\home\t\.faforever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /seraphim /log /home/t/.faforever/logs/game.log /gpgnet 127.0.0.1:19322 /mean 857.077 /deviation 67.0128 /savereplay gpgnet://127.0.0.1:44677/10020663/tatsu.SCFAreplay /country FR /clan BPT /numgames 2214 /team 1 /players 2

Callstack:
    unavailable.

Last 100 lines of log...

warning: Running "Z:\home\t\.faforever\bin\init.lua" failed: cannot read init_faf.lua: No such file or directory
         stack traceback:
         	[C]: in function `dofile'
         	Z:\home\t\.faforever\bin\init.lua(1): in main chunk
```

**Comment by douglasg14b** [comment]
Having this issue, but `ForgedAlliance.exe` is already executable.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/fa/blob/develop/SupComDataPath.lua should lie here 
http://content.faforever.com/legacy-featured-mod-files/updates_faf_files/SupComDataPath.lua
but it does not, instead some really old file lies there

**Comment by 1-alex98** [comment]
On the server there is still the old version of 2011 XD

**Comment by 1-alex98** [comment]
So the issue is the java api updates everything that is in a folder right. Because it packs those into .nx2 files (which are basically zips) but it does not care about any files that are in the top level like init.lua or SupComPath.lua . Those have never been updated and are still the same as they were 2011. Apart from the init.lua... it seems some ppl updated it by hand 
![grafik](https://user-images.githubusercontent.com/19996713/67633437-2dedc300-f8b0-11e9-9105-f6945a847024.png)
Or whatever there was before the java-api updated it. And i think before we had the java api auto deploy faf featured mod it was done by hand. 

So what does this mean:
- Either we add updates by hand whenever init.lua changes(the others are probably gonna stay the same forever) and the SupComPath.lua of cause needs to be updated once.
- Or we start updating those files that are in the top directory as well. Automatically. 

Further if we do one of the above things that is not gonna change/fix ladder:
Ladder is basically faf featured mod, it is just a copy of it, it is just called differently and because of that the client selects the init_ladder1v1.lua instead of the init_faf.lua . But both files can not be found in this git they lie on the server and they lie only on the server. The init_faf.lua has been updated by hand some times as it seems looking into the db. But the init_ladder1v1.lua has never been updated since the start of FAF. 

How do we fix that:
1. We rename init.lua in the fa repo to init_faf.lua
2. We copy the init_ladder1v1.lua from the server and put it in the fa repo, including the one line fix that is mentioned in the issue above 
```
dofile(InitFileDir .. '\\init_faf.lua')
instead of
dofile('init_faf.lua')
```
3. We either update by hand or automatically as described above

**Comment by 1-alex98** [comment]
@Brutus5000 as a first step we should change fa repo. But this would need to be done by u as i have no rights to the repo nor access to the server. And then u need to decide if we build that into auto deploy or if we update it by hand.

What I suggest is that we update the two files that cause ladder to not work on linux by hand. Update cycle of fa might take up to a year.
Would be SupComPath.lua, init_ladder1v1.lua. Where SupComPath.lua just needs to be replaced with what is in the git fa repo and ini_ladder1v1.lua needs the one line replaced :
```
dofile(InitFileDir .. '\\init_faf.lua')
instead of
dofile('init_faf.lua')
```
Update those by hand also change the git fa repo as suggested and then change the java api to also detect and deploy future changes on these files.

**Comment by Brutus5000** [comment]
Did that. Broke **_all_** other featured mods. ⛔️ 
Someone needs to align this with all other featured mods as it seem.s

**Comment by 1-alex98** [comment]
But u also updated init.lua from the faf repo right. I mean to fix linux issue changing the one line would be enough for starters 🤔 I mean I tested the one liners on windows and worked flawlessly

**Comment by iczero** [comment]
It seems to be fixed now
