### ISSUE TITLE
Add replay rating to the replay search

### ISSUE THREAD

**Issue by JaggedAppliance** [micheljung/faf-java-api#652]
There is no way to search for replays which have a rating except by looking at the most highly rated games. This is not really a search though, simply a list of replays. 

I hope that if this were implemented the replay rating feature would be used more, it is not used very often at the moment.

**Comment by Sheikah45** [comment]
This is a bit more of an api issue, because at the moment there is no way to search by number of stars which is the expected behavior

**Comment by bukajsytlos** [comment]
[this](https://api.faforever.com/data/game?sort=-id&filter=reviewsSummary.score==4) isn't it?

**Comment by JaggedAppliance** [comment]
If that's it @Sheikah45 would that mean it is a client issue then?

**Comment by Sheikah45** [comment]
> [this](https://api.faforever.com/data/game?sort=-id&filter=reviewsSummary.score==4) isn't it?

That is not the average number of stars it is the sum of all the stars given. So not what people would expect since it just grows with number of reviews 

Additionally the lower_bound property is the [Wilson score confidence interval](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval)

Which doesn't line up with the number of stars. So for example you would find the ones returned by that query to not all have 4 stars. Had tried using that in the past but it just confused people.

**Comment by bukajsytlos** [comment]
@Sheikah45  so doing score/reviews represents average star rating?

**Comment by Sheikah45** [comment]
That is correct yes
